/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        headline: ['Ubuntu', 'sans-serif'],
        display:  ['Ubuntu', 'sans-serif'],
        body:     ['Ubuntu', 'sans-serif'],
        label:    ['Ubuntu', 'sans-serif'],
      },
      colors: {
        'primary':                    '#4f378a',
        'on-primary':                 '#ffffff',
        'primary-container':          '#6750a4',
        'on-primary-container':       '#e0d2ff',
        'primary-fixed':              '#e9ddff',
        'primary-fixed-dim':          '#cfbcff',
        'on-primary-fixed':           '#22005d',
        'on-primary-fixed-variant':   '#4f378a',
        'inverse-primary':            '#cfbcff',
        'secondary':                  '#63597c',
        'on-secondary':               '#ffffff',
        'secondary-container':        '#e1d4fd',
        'on-secondary-container':     '#645a7d',
        'secondary-fixed':            '#e9ddff',
        'secondary-fixed-dim':        '#cdc0e9',
        'on-secondary-fixed':         '#1f1635',
        'on-secondary-fixed-variant': '#4b4263',
        'tertiary':                   '#765b00',
        'on-tertiary':                '#ffffff',
        'tertiary-container':         '#c9a74d',
        'on-tertiary-container':      '#503d00',
        'tertiary-fixed':             '#ffdf93',
        'tertiary-fixed-dim':         '#e7c365',
        'on-tertiary-fixed':          '#241a00',
        'on-tertiary-fixed-variant':  '#594400',
        'error':                      '#ba1a1a',
        'on-error':                   '#ffffff',
        'error-container':            '#ffdad6',
        'on-error-container':         '#93000a',
        'background':                 '#fdf7ff',
        'on-background':              '#1d1b20',
        'surface':                    '#fdf7ff',
        'surface-dim':                '#ded8e0',
        'surface-bright':             '#fdf7ff',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f8f2fa',
        'surface-container':          '#f2ecf4',
        'surface-container-high':     '#ece6ee',
        'surface-container-highest':  '#e6e0e9',
        'on-surface':                 '#1d1b20',
        'on-surface-variant':         '#494551',
        'surface-variant':            '#e6e0e9',
        'outline':                    '#7a7582',
        'outline-variant':            '#cbc4d2',
        'inverse-surface':            '#322f35',
        'inverse-on-surface':         '#f5eff7',
        'surface-tint':               '#6750a4',
        'success':                    '#1a7f4b',
        'on-success':                 '#ffffff',
        'success-container':          '#dcfce7',
        'warning':                    '#765b00',
        'warning-container':          '#ffdf93',
      },
      borderRadius: {
        'sm':      '0.25rem',
        'DEFAULT': '0.5rem',
        'md':      '0.75rem',
        'lg':      '1rem',
        'xl':      '1.5rem',
        'full':    '9999px',
      },
      boxShadow: {
        'sm':  '0 1px 3px 0 rgba(0,0,0,0.06), 0 1px 2px 0 rgba(0,0,0,0.04)',
        'md':  '0 4px 6px -1px rgba(0,0,0,0.07), 0 2px 4px -1px rgba(0,0,0,0.04)',
        'lg':  '0 10px 15px -3px rgba(0,0,0,0.08), 0 4px 6px -2px rgba(0,0,0,0.04)',
        'xl':  '0 20px 25px -5px rgba(0,0,0,0.08), 0 10px 10px -5px rgba(0,0,0,0.03)',
      },
    },
  },
  plugins: [],
}